### ISSUE TITLE
Retard sur rendu

### ISSUE THREAD

**Issue by natos33** [PolytechLyon/isi3-tp4-kebab-kata-mounier-jolivet-tp4#2]
Bonjour,

Nous avons appris ce matin que ce tp était à rendre ce soir et non vendredi comme nous le pensions. C'est pourquoi, afin de ne pas bacler le travail, nous risquons de le rendre légèrement en retard dans la soirée et non à 18h comme demandé.

Nous nous excusons pour les problèmes engendrés

**Comment by k33g** [comment]
c'est ok
bonnes vacances

**Comment by mounieju** [comment]
D'accord, merci !
